# blocks

include ../../Makeconf.win

FLAGS = -g -Wall -I. -I.. -I${INC_DIR}
CC = gcc ${FLAGS}

OFILES = 	\
	binary.o	\
	block.o	\
	browserfont.o	\
	button.o	\
	character.o	\
	cxform.o	\
	dbl.o	\
	error.o	\
	fdbfont.o	\
	fileattrs.o	\
	fillstyle.o	\
	filter.o	\
	flv.o	\
	font.o	\
	fontinfo.o	\
	fromswf.o	\
	gradient.o	\
	imports.o	\
	input.o	\
	jpeg.o	\
	linestyle.o	\
	matrix.o	\
	metadata.o	\
	method.o	\
	morph.o	\
	mp3.o	\
	output.o	\
	outputblock.o	\
	placeobject.o	\
	protect.o	\
	rect.o	\
	scalinggrid.o	\
	scenedata.o	\
	scriptlimits.o	\
	shape.o	\
	sound.o	\
	soundinstance.o	\
	soundstream.o	\
	sprite.o	\
	symbolclass.o	\
	tabindex.o	\
	text.o	\
	textfield.o	\
	utf8.o	\
	videostream.o	\
	gifdbl.o	\
	pngdbl.o	\
	ttffont.o	\
	bitmap.o	\
	action.o	

all: ${OFILES}

clean:
	rm -f *.o