# actioncompiler

CC = gcc -g -Wall -I..

OFILES = 	\
	assembler.o \
	compile.o \
	compileaction.o \
	lex.swf4.o \
	lex.swf5.o \
	listaction.o \
	swf4compiler.tab.o \
	swf5compiler.tab.o

all: ${OFILES}

clean:
	rm -f *.o